defaults:
  - hydra: default
  - data: learner
  - model: learner
  - trainer: default
  - callbacks: default
  # Use experiment configs to add some overrides
  - experiment: null
  # Overrides must be last
  - override hydra/launcher: joblib

seed: 43

tags: ["${data.name}", "${model.name}"]

trainer:
  logger:
    tags: ${tags}