version: "3"

# You can also ask Task to include .env like files by using the dotenv: setting:
dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

# If `--` is given in the CLI, all following parameters are added to a special .CLI_ARGS variable.
# This is useful to forward arguments to another command.

tasks:

  check-config:
    desc: Check Hydra configuration
    cmds:
      - python scarf/train.py --cfg all --resolve {{.CLI_ARGS}}

  wandb:
    desc: Login to Weights & Biases
    cmds:
      - wandb login $WANDB_KEY

  preprocess:
    desc: Preprocess raw data
    cmds:
      - python scarf/preprocess.py {{.CLI_ARGS}}

  make-valid:
    desc: Generate static validation data for pre-training
    cmds:
      - python -c "from scarf.data import make_static_validation_data; make_static_validation_data()"

  train-self:
    desc: Train the encoder module
    cmds:
      - python scarf/train.py {{.CLI_ARGS}}

  train:
    desc: Train a model
    cmds:
      - python scarf/train.py {{.CLI_ARGS}}