name: gradient-booster

estimator:
  _target_: sklearn.ensemble.GradientBoostingClassifier
  learning_rate: 0.01
  n_estimators: 500
  subsample: 0.9
  random_state: ${seed}
  validation_fraction: 0.1
  n_iter_no_change: 10