defaults:
  - default

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: valid-loss
  min_delta: 0.001
  patience: 3
  check_on_train_epoch_end: False

model_checkpoint:
  monitor: train-loss
